{ config, lib, pkgs, username ? "saleh", ... }:

{
  # Copy this template to hosts/<hostname>.nix, then replace the hardware import
  # with the file generated by nixos-generate-config on the target machine.
  imports = [
    ./hardware-configuration.nix
  ];

  networking.hostName = lib.mkDefault "new-computer";
  hardware.bluetooth.enable = lib.mkDefault true;

  boot.loader.systemd-boot.enable = lib.mkDefault false;
  boot.loader.grub = {
    enable = lib.mkDefault true;
    efiSupport = lib.mkDefault true;
    device = lib.mkDefault "nodev";
    useOSProber = lib.mkDefault true;
    configurationLimit = lib.mkDefault 10;
  };

  boot.loader.efi = {
    canTouchEfiVariables = lib.mkDefault true;
    efiSysMountPoint = lib.mkDefault "/boot/efi";
  };

  boot.supportedFilesystems = [ "btrfs" "vfat" "exfat" "ntfs" ];

  services.printing.enable = lib.mkDefault true;
  services.udisks2.enable = lib.mkDefault true;
  services.gvfs.enable = lib.mkDefault true;
  services.fstrim.enable = lib.mkDefault true;

  services.power-profiles-daemon.enable = lib.mkDefault true;
  powerManagement.enable = lib.mkDefault true;
  services.upower.enable = lib.mkDefault true;

  programs.niri.enable = lib.mkDefault true;
  services.greetd.enable = lib.mkDefault true;
  programs.regreet = {
    enable = lib.mkDefault true;
    cageArgs = [ "-s" "-d" "-m" "extend" ];
  };

  hardware.graphics.enable = lib.mkDefault true;

  # DisplayLink dock support, disabled by default. Uncomment when the target
  # machine needs it, and keep the matching unfree allowlist below enabled too.
  # services.xserver.videoDrivers = [ "displaylink" "modesetting" ];
  # systemd.services.dlm.wantedBy = [ "multi-user.target" ];

  security.polkit.enable = lib.mkDefault true;

  programs.appimage.enable = lib.mkDefault true;
  programs.appimage.binfmt = lib.mkDefault true;

  environment.sessionVariables = {
    NIXOS_OZONE_WL = "1";
  };

  xdg.portal = {
    enable = lib.mkDefault true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-gtk
    ];
  };

  security.rtkit.enable = lib.mkDefault true;
  services.pipewire = {
    enable = lib.mkDefault true;
    pulse.enable = lib.mkDefault true;
    alsa.enable = lib.mkDefault true;
    alsa.support32Bit = lib.mkDefault true;
  };

  virtualisation.docker.storageDriver = lib.mkDefault "btrfs";

  users.users.${username} = {
    isNormalUser = true;
    extraGroups = [
      "nixcfg"
      "wheel"
      "networkmanager"
      "docker"
    ];
    packages = with pkgs; [
      tree
    ];
  };

  # DisplayLink requires unfree packages. Disabled by default with the driver.
  # nixpkgs.config.allowUnfreePredicate = pkg:
  #   builtins.elem (pkgs.lib.getName pkg) [
  #     "displaylink"
  #     "evdi"
  #     "steam-unwrapped"
  #   ];

  environment.systemPackages = with pkgs; [
    niri
    xwayland-satellite
    fuzzel
    swaybg

    alacritty
    wl-clipboard
    grim
    slurp
    wezterm
    ghostty

    pamixer
    pavucontrol
    brightnessctl
    playerctl

    nautilus
    networkmanagerapplet
    wireguard-tools
    proton-vpn

    polkit
    kdePackages.polkit-kde-agent-1

    swaylock

    adwaita-icon-theme
    gnome-themes-extra

    xdg-desktop-portal
    xdg-desktop-portal-gtk

    chromium

    efibootmgr
    os-prober
    gparted
  ];
}
